/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.11.4")
    implementation("org.springdoc:springdoc-openapi-webmvc-core:1.6.14")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.10")
    implementation("org.springframework.data:spring-data-jpa:2.4.3")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation("com.ubiqsecurity:ubiqsecurity:2.1.2")
    implementation("com.ubiqsecurity:ubiqsecurity-fpe:2.1.1")
    implementation("org.springframework:spring-webflux:5.3.3")
    implementation("io.springfox:springfox-swagger2:2.9.2")
    implementation("io.springfox:springfox-swagger-ui:2.9.2")
    implementation("org.json:json:20231013")
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0")
    implementation("org.bouncycastle:bcpkix-jdk15on:1.50")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.2")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "security"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
