apiVersion: v1
kind: Service
metadata:
  name: en-dec-service
  namespace: s3
spec:
  type: NodePort
  selector:
    app: enc-dec
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30720